name: Quality Checks

on:
  push:
    branches: ["devel", "master", "dev/*", "release/*", "feature/*", "hotfix/*"]
  pull_request:
    branches: ["devel", "master", "dev/*", "release/*", "feature/*", "hotfix/*"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install flake8 black sqlfluff yamllint pylint
          npm install -g markdownlint-cli

      - name: Run all linting checks
        run: make lint

  test-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run TestDocumentation tests
        run: pytest test/core/test_documentation.py -k "TestDocumentation"

  test-core:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Pull LFS objects
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-mock

      - name: Run core tests
        run: |
          pytest test/core/test_config.py -k "TestConfig"
          pytest test/core/test_util.py -k "TestUtil"
          pytest test/core/test_views_structure.py -k "TestViews"
          pytest test/core/test_connector.py -k "TestTelemetrySender"
      - name: Run OTEL tests
        run: |
          pytest test/otel/test_events.py -k "TestEvents"
          pytest test/otel/test_otel_manager.py -k "TestOtelManager"

  test-plugins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Git LFS
        run: git lfs install

      - name: Pull LFS objects
        run: git lfs pull

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.12"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest-mock

      - name: Run plugin tests
        run: pytest test/plugins/
